Repository Arthur-Sbeghen/Rpgenius, pull requests merged in 2025-07, with the labels that each got.

#16 Altera Organização
  api/app/Http/Controllers/MesaController.php
  api/routes/api.php
  api/routes/web.php
  app/src/app/table/page.tsx
  app/src/components/TableActions/TableCreate/TableCreate.tsx
  app/src/components/TableActions/TableCreate/TableCreateModal.tsx
  app/src/components/TableActions/TableDelete.tsx
  app/src/components/TableActions/TableEdit/TableEditModal.tsx
  app/src/components/TableActions/TableEdit/tableEditModal.module.css
Labels: Melhoria

#18 FT-80-75
  app/src/app/home/page.tsx
  app/src/app/home/style.css
  app/src/app/layout.tsx
  app/src/components/Footer/Footer.tsx
  app/src/components/Footer/style.css
  app/src/components/Header/style.css
  app/src/components/InputCheckbox/InputCheckbox.tsx
  app/src/components/InputCheckbox/style.css
  app/src/components/InputDate/InputDate.tsx
  app/src/components/InputDate/style.css
  app/src/components/InputEmail/InputEmail.tsx
  app/src/components/InputEmail/style.css
  app/src/components/InputFile/InputFile.tsx
  app/src/components/InputFile/style.css
  app/src/components/InputNumber/InputNumber.tsx
  app/src/components/InputNumber/style.css
  app/src/components/InputPassword/InputPassword.tsx
  app/src/components/InputPassword/style.css
  app/src/components/InputRadio/InputRadio.tsx
  app/src/components/InputRadio/style.css
  app/src/components/InputText/InputText.tsx
  app/src/components/InputText/style.css
  app/src/components/Textarea/Textarea.tsx
  app/src/components/Textarea/style.css
Labels: Interface, Melhoria

#19 inicio-ficha
  api/app/Http/Controllers/MesaController.php
  api/app/Models/Table.php
  app/src/app/table/page.tsx
  app/src/app/table/schema.ts
  app/src/app/table/styles.css
  app/src/components/CharacterCreate/CharacterCreateForm.tsx
  app/src/components/CharacterCreate/CharacterCreateModal.tsx
  app/src/components/CharacterCreate/DiceRoller.tsx
  app/src/components/TableActions/RemoveFromTable.tsx
  app/src/components/TableActions/TableLeave.tsx
  app/src/components/TableActions/tableCreateModal.module.css
Labels: Cria Funcionalidade
